In [40]:
import json
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np

In [4]:
activations = pd.read_pickle('unit activations.pkl')

with open('result_0.json', 'r') as file:
    test_1_history = json.load(file)

In [9]:
len(activations)

967

In [12]:
activations = activations[367:]

In [14]:
relu_ = activations[:150]
lrelu_ = activations[150:300]
elu_ = activations[450:]

In [36]:
relu_mean = []

for i in range(3):
    folds = []
    for items in relu_[50 * i:50 * (i + 1)]:
        means = np.mean(items)

        folds.append(means)

    relu_mean.append(folds)

In [37]:
relu_mean = np.array(relu_mean)
relu_mean

array([[ 90.123764,  88.94438 ,  90.114136,  88.399796,  88.5267  ,
        102.83259 , 103.058   ,  97.50385 , 106.30205 , 101.61214 ,
        100.51352 , 105.921814, 106.691216, 112.03551 , 102.96743 ,
        116.48104 , 109.70157 , 118.28765 , 113.83508 , 115.23047 ,
        113.39899 , 121.249275, 118.81743 , 119.652245, 114.752426,
        118.93939 , 116.76643 , 122.419174, 123.94943 , 123.5405  ,
        129.28818 , 123.90877 , 131.15244 , 128.6948  , 131.59851 ,
        131.24323 , 129.02031 , 129.66647 , 133.41113 , 134.58525 ,
        128.46161 , 128.74489 , 133.8189  , 131.79407 , 137.31995 ,
        137.8121  , 138.6327  , 136.61269 , 135.81017 , 139.27635 ],
       [ 95.268005,  92.61374 ,  90.74554 ,  90.372246,  84.26487 ,
         92.45163 ,  89.455246,  90.2386  ,  87.34253 ,  93.99559 ,
         87.18811 ,  88.207016,  90.48443 ,  90.72744 ,  91.074005,
         92.24722 ,  98.41726 ,  96.990814, 101.627716,  97.10877 ,
        101.779976,  99.82966 ,  99.71062 , 101

In [33]:
relu_mean.shape

(3, 50)

In [38]:
lrelu_mean = []

for i in range(3):
    folds = []
    for items in lrelu_[50 * i:50 * (i + 1)]:
        means = np.mean(items)

        folds.append(means)

    lrelu_mean.append(folds)

lrelu_mean = np.array(lrelu_mean)
lrelu_mean

array([[ 99.84817 ,  96.9302  ,  96.968094, 106.03447 ,  99.06114 ,
         92.89716 ,  89.66535 ,  86.163704,  88.11062 ,  88.86823 ,
         92.23675 ,  93.0318  ,  85.80714 ,  92.00114 ,  91.58269 ,
         97.058   ,  85.35386 ,  86.98894 ,  83.12242 ,  87.01173 ,
         88.628845,  82.42124 ,  87.44586 ,  94.94446 ,  86.73097 ,
         96.1173  ,  89.12599 ,  89.28699 ,  89.45685 ,  85.91148 ,
         87.75904 ,  83.43044 ,  92.99565 ,  90.94446 ,  88.98198 ,
         91.29175 ,  91.00495 ,  91.15196 ,  93.038475,  88.685005,
         88.17186 ,  95.49504 ,  88.1922  ,  91.09245 ,  94.811584,
         92.39919 ,  87.9577  ,  91.791595,  88.352036,  88.396965],
       [ 79.225945,  82.70088 ,  82.3282  ,  80.96227 ,  88.05049 ,
         87.11471 ,  90.21814 ,  98.75969 ,  98.350784,  98.5383  ,
         98.324005,  95.96678 ,  99.84396 , 103.3858  , 106.40064 ,
         99.64392 , 101.179756, 108.584915, 120.313896, 113.97476 ,
        119.39732 , 113.174255, 120.09975 , 118

In [39]:
elu_mean = []

for i in range(3):
    folds = []
    for items in elu_[50 * i:50 * (i + 1)]:
        means = np.mean(items)

        folds.append(means)

    elu_mean.append(folds)

elu_mean = np.array(elu_mean)
elu_mean

array([[ 67.72038 ,  73.37166 ,  71.67843 ,  74.35556 ,  79.51431 ,
         78.87216 ,  80.09571 ,  74.85433 ,  84.53505 ,  85.56257 ,
         82.256096,  85.33247 ,  84.806595,  82.9267  ,  83.09772 ,
         92.75926 ,  88.65173 ,  88.74347 ,  89.78131 ,  91.41675 ,
         91.27629 ,  94.79983 ,  95.78542 ,  97.51865 ,  98.05542 ,
         93.65514 ,  98.621216, 102.819626, 102.63556 , 107.062904,
        103.1837  , 104.201996, 111.316986, 114.25785 , 111.87686 ,
        108.50191 , 112.5974  , 112.898224, 115.877396, 114.17717 ,
        114.01343 , 114.39421 , 114.47803 , 110.66212 , 113.77231 ,
        115.68034 , 121.5474  , 125.878204, 117.10979 , 120.55382 ],
       [ 52.779873,  58.95687 ,  63.03646 ,  63.695595,  67.17801 ,
         68.58739 ,  68.96928 ,  68.90316 ,  75.052536,  70.81477 ,
         72.3066  ,  72.971725,  74.97647 ,  77.5213  ,  75.362885,
         80.4135  ,  77.42697 ,  77.17384 ,  78.15776 ,  81.224525,
         79.703835,  82.86022 ,  84.97043 ,  87

In [55]:
x = np.arange(0, 50)
y = np.mean(relu_mean, axis=0)
y_std = np.std(relu_mean, axis=0)

In [86]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=x,
                         y=np.mean(relu_mean, axis=0) + np.std(relu_mean, axis=0),
                         fill=None,
                         mode='lines',
                         line_color='rgba(242, 160, 220,0.2)',
                         hoverinfo="skip",
                         showlegend=False))
fig.add_trace(go.Scatter(x=x,
                         y=np.mean(relu_mean, axis=0) - np.std(relu_mean, axis=0),
                         fill='tonexty',  # fill area between trace0 and trace1
                         mode='lines',
                         line_color='rgba(242, 160, 220,0.2)',
                         hoverinfo="skip",
                         showlegend=False))
fig.add_trace(go.Scatter(x=x,
                         y=np.mean(relu_mean, axis=0),
                         line=dict(color='rgb(242, 160, 220)'),
                         mode='lines',
                         name='relu'
                         ))

fig.add_trace(go.Scatter(x=x,
                         y=np.mean(lrelu_mean, axis=0) + np.std(lrelu_mean, axis=0),
                         fill=None,
                         mode='lines',
                         line_color='rgba(72, 217, 149,0.2)',
                         hoverinfo="skip",
                         showlegend=False))
fig.add_trace(go.Scatter(x=x,
                         y=np.mean(lrelu_mean, axis=0) - np.std(lrelu_mean, axis=0),
                         fill='tonexty',  # fill area between trace0 and trace1
                         mode='lines',
                         line_color='rgba(72, 217, 149,0.2)',
                         hoverinfo="skip",
                         showlegend=False))
fig.add_trace(go.Scatter(x=x,
                         y=np.mean(lrelu_mean, axis=0),
                         line=dict(color='rgb(72, 217, 149)'),
                         mode='lines',
                         name='lrelu'
                         ))

fig.add_trace(go.Scatter(x=x,
                         y=np.mean(elu_mean, axis=0) + np.std(elu_mean, axis=0),
                         fill=None,
                         mode='lines',
                         line_color='rgba(242, 94, 94, 0.2)',
                         hoverinfo="skip",
                         showlegend=False))
fig.add_trace(go.Scatter(x=x,
                         y=np.mean(elu_mean, axis=0) - np.std(elu_mean, axis=0),
                         fill='tonexty',  # fill area between trace0 and trace1
                         mode='lines',
                         line_color='rgba(242, 94, 94, 0.2)',
                         hoverinfo="skip",
                         showlegend=False))
fig.add_trace(go.Scatter(x=x,
                         y=np.mean(elu_mean, axis=0),
                         line=dict(color='rgb(242, 94, 94)'),
                         mode='lines',
                         name='elu'
                         ))

fig.update_layout(height=800,
                  yaxis_title='average unit activation',
                  xaxis_title='epoch')

fig.write_json('../../../images/activation/elus/avg-unit-active.html')

fig.show()