In [27]:
stopwords = ['x','y','your','yours','yourself','yourselves','you','yond','yonder','yon','ye','yet','z','zillion','j','u','umpteen','usually','us','username','uponed','upons','uponing','upon','ups','upping','upped','up','unto','until','unless','unlike','unliker','unlikest','under','underneath','use','used','usedest','r','rath','rather','rathest','rathe','re','relate','related','relatively','regarding','really','res','respecting','respectively','q','quite','que','qua','n','neither','neaths','neath','nethe','nethermost','necessary','necessariest','necessarier','never','nevertheless','nigh','nighest','nigher','nine','noone','nobody','nobodies','nowhere','nowheres','no','noes','nor','nos','no-one','none','not','notwithstanding','nothings','nothing','nathless','natheless','t','ten','tills','till','tilled','tilling','to','towards','toward','towardest','towarder','together','too','thy','thyself','thus','than','that','those','thou','though','thous','thouses','thoroughest','thorougher','thorough','thoroughly','thru','thruer','thruest','thro','through','throughout','throughest','througher','thine','this','thises','they','thee','the','then','thence','thenest','thener','them','themselves','these','therer','there','thereby','therest','thereafter','therein','thereupon','therefore','their','theirs','thing','things','three','two','o','oh','owt','owning','owned','own','owns','others','other','otherwise','otherwisest','otherwiser','of','often','oftener','oftenest','off','offs','offest','one','ought','oughts','our','ours','ourselves','ourself','out','outest','outed','outwith','outs','outside','over','overallest','overaller','overalls','overall','overs','or','orer','orest','on','oneself','onest','ons','onto','a','atween','at','athwart','atop','afore','afterward','afterwards','after','afterest','afterer','ain','an','any','anything','anybody','anyone','anyhow','anywhere','anent','anear','and','andor','another','around','ares','are','aest','aer','against','again','accordingly','abaft','abafter','abaftest','abovest','above','abover','abouter','aboutest','about','aid','amidst','amid','among','amongst','apartest','aparter','apart','appeared','appears','appear','appearing','appropriating','appropriate','appropriatest','appropriates','appropriater','appropriated','already','always','also','along','alongside','although','almost','all','allest','aller','allyou','alls','albeit','awfully','as','aside','asides','aslant','ases','astrider','astride','astridest','astraddlest','astraddler','astraddle','availablest','availabler','available','aughts','aught','vs','v','variousest','variouser','various','via','vis-a-vis','vis-a-viser','vis-a-visest','viz','very','veriest','verier','versus','k','g','go','gone','good','got','gotta','gotten','get','gets','getting','b','by','byandby','by-and-by','bist','both','but','buts','be','beyond','because','became','becomes','become','becoming','becomings','becominger','becomingest','behind','behinds','before','beforehand','beforehandest','beforehander','bettered','betters','better','bettering','betwixt','between','beneath','been','below','besides','beside','m','my','myself','mucher','muchest','much','must','musts','musths','musth','main','make','mayest','many','mauger','maugre','me','meanwhiles','meanwhile','mostly','most','moreover','more','might','mights','midst','midsts','h','huh','humph','he','hers','herself','her','hereby','herein','hereafters','hereafter','hereupon','hence','hadst','had','having','haves','have','has','hast','hardly','hae','hath','him','himself','hither','hitherest','hitherer','his','how-do-you-do','however','how','howbeit','howdoyoudo','hoos','hoo','w','woulded','woulding','would','woulds','was','wast','we','wert','were','with','withal','without','within','why','what','whatever','whateverer','whateverest','whatsoeverer','whatsoeverest','whatsoever','whence','whencesoever','whenever','whensoever','when','whenas','whether','wheen','whereto','whereupon','wherever','whereon','whereof','where','whereby','wherewithal','wherewith','whereinto','wherein','whereafter','whereas','wheresoever','wherefrom','which','whichever','whichsoever','whilst','while','whiles','whithersoever','whither','whoever','whosoever','whoso','whose','whomever','s','syne','syn','shalling','shall','shalled','shalls','shoulding','should','shoulded','shoulds','she','sayyid','sayid','said','saider','saidest','same','samest','sames','samer','saved','sans','sanses','sanserifs','sanserif','so','soer','soest','sobeit','someone','somebody','somehow','some','somewhere','somewhat','something','sometimest','sometimes','sometimer','sometime','several','severaler','severalest','serious','seriousest','seriouser','senza','send','sent','seem','seems','seemed','seemingest','seeminger','seemings','seven','summat','sups','sup','supping','supped','such','since','sine','sines','sith','six','stop','stopped','p','plaintiff','plenty','plenties','please','pleased','pleases','per','perhaps','particulars','particularly','particular','particularest','particularer','pro','providing','provides','provided','provide','probably','l','layabout','layabouts','latter','latterest','latterer','latterly','latters','lots','lotting','lotted','lot','lest','less','ie','ifs','if','i','info','information','itself','its','it','is','idem','idemer','idemest','immediate','immediately','immediatest','immediater','in','inwards','inwardest','inwarder','inward','inasmuch','into','instead','insofar','indicates','indicated','indicate','indicating','indeed','inc','f','fact','facts','fs','figupon','figupons','figuponing','figuponed','few','fewer','fewest','frae','from','failing','failings','five','furthers','furtherer','furthered','furtherest','further','furthering','furthermore','fourscore','followthrough','for','forwhy','fornenst','formerly','former','formerer','formerest','formers','forbye','forby','fore','forever','forer','fores','four','d','ddays','dday','do','doing','doings','doe','does','doth','downwarder','downwardest','downward','downwards','downs','done','doner','dones','donest','dos','dost','did','differentest','differenter','different','describing','describe','describes','described','despiting','despites','despited','despite','during','c','cum','circa','chez','cer','certain','certainest','certainer','cest','canst','cannot','cant','cants','canting','cantest','canted','co','could','couldst','comeon','comeons','come-ons','come-on','concerning','concerninger','concerningest','consequently','considering','e','eg','eight','either','even','evens','evenser','evensest','evened','evenest','ever','everyone','everything','everybody','everywhere','every','ere','each','et','etc','elsewhere','else','ex','excepted','excepts','except','excepting','exes','enough']

## Getting started with tokenization

In [30]:
import string
import tensorflow as tf
import tensorflow_datasets as tfds
from bs4 import BeautifulSoup
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
sentences = ['Today is a sunny day',
             'Today is a rainy day']

tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

In [3]:
word_index

{'today': 1, 'is': 2, 'a': 3, 'day': 4, 'sunny': 5, 'rainy': 6}

## Turning sequences into sequences

In [5]:
sentences = ['Today is a sunny day',
             'Today is a rainy day',
             'Is it sunny today?']

tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentences)

In [6]:
sequences

[[1, 2, 3, 4, 5], [1, 2, 3, 6, 5], [2, 7, 4, 1]]

##### out of vocabulary tokens

In [7]:
test_data = ['Today is a snowy day',
             'Will it be rainy tomorrow?']
test_sequences = tokenizer.texts_to_sequences(test_data)

In [8]:
test_sequences

[[1, 2, 3, 5], [7, 6]]

In [9]:
tokenizer = Tokenizer(num_words=100, oov_token='<oov>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentences)
test_sequences = tokenizer.texts_to_sequences(test_data)

In [10]:
word_index

{'<oov>': 1,
 'today': 2,
 'is': 3,
 'a': 4,
 'sunny': 5,
 'day': 6,
 'rainy': 7,
 'it': 8}

In [11]:
test_sequences

[[2, 3, 4, 1, 6], [1, 8, 1, 7, 1]]

##### padding

In [12]:
sentences = [
    'Today is a sunny day',
    'Today is a rainy day',
    'Is it sunny today?',
    'I really enjoyed walking in the snow today'
]

tokenizer = Tokenizer(num_words=100, oov_token='<oov>')
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentences)

In [13]:
sequences

[[2, 3, 4, 5, 6],
 [2, 3, 4, 7, 6],
 [3, 8, 5, 2],
 [9, 10, 11, 12, 13, 14, 15, 2]]

In [15]:
padded = pad_sequences(sequences)

In [16]:
padded

array([[ 0,  0,  0,  2,  3,  4,  5,  6],
       [ 0,  0,  0,  2,  3,  4,  7,  6],
       [ 0,  0,  0,  0,  3,  8,  5,  2],
       [ 9, 10, 11, 12, 13, 14, 15,  2]])

In [17]:
padded = pad_sequences(sequences, padding='post')

In [18]:
padded

array([[ 2,  3,  4,  5,  6,  0,  0,  0],
       [ 2,  3,  4,  7,  6,  0,  0,  0],
       [ 3,  8,  5,  2,  0,  0,  0,  0],
       [ 9, 10, 11, 12, 13, 14, 15,  2]])

In [19]:
padded = pad_sequences(sequences, padding='post', maxlen=6)

In [20]:
padded

array([[ 2,  3,  4,  5,  6,  0],
       [ 2,  3,  4,  7,  6,  0],
       [ 3,  8,  5,  2,  0,  0],
       [11, 12, 13, 14, 15,  2]])

In [21]:
padded = pad_sequences(sequences, padding='post', maxlen=6, truncating='post')

In [22]:
padded

array([[ 2,  3,  4,  5,  6,  0],
       [ 2,  3,  4,  7,  6,  0],
       [ 3,  8,  5,  2,  0,  0],
       [ 9, 10, 11, 12, 13, 14]])

## Remove stopwords and cleaning text

In [26]:
imdb_sentences = []
train_data = tfds.as_numpy(tfds.load('imdb_reviews',split='train'))

for item in train_data:
    imdb_sentences.append(str(item['text']))

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/3 [00:00<?, ? splits/s]

Generating train examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\hewar\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteGZ4GNH\imdb_reviews-train…

Generating test examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\hewar\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteGZ4GNH\imdb_reviews-test.…

Generating unsupervised examples...: 0 examples [00:00, ? examples/s]

Shuffling C:\Users\hewar\tensorflow_datasets\imdb_reviews\plain_text\1.0.0.incompleteGZ4GNH\imdb_reviews-unsup…

Dataset imdb_reviews downloaded and prepared to C:\Users\hewar\tensorflow_datasets\imdb_reviews\plain_text\1.0.0. Subsequent calls will reuse this data.


In [28]:
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(imdb_sentences)

sequences = tokenizer.texts_to_sequences(imdb_sentences)

In [29]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'br': 7,
 'in': 8,
 'it': 9,
 'i': 10,
 'this': 11,
 'that': 12,
 'was': 13,
 'as': 14,
 'for': 15,
 'with': 16,
 'movie': 17,
 'but': 18,
 'film': 19,
 "'s": 20,
 'on': 21,
 'you': 22,
 'not': 23,
 'are': 24,
 'his': 25,
 'he': 26,
 'have': 27,
 'be': 28,
 'one': 29,
 'all': 30,
 'at': 31,
 'by': 32,
 'they': 33,
 'an': 34,
 'who': 35,
 'so': 36,
 'from': 37,
 'like': 38,
 'her': 39,
 "'t": 40,
 'or': 41,
 'just': 42,
 'there': 43,
 'about': 44,
 'out': 45,
 "'": 46,
 'has': 47,
 'if': 48,
 'some': 49,
 'what': 50,
 'good': 51,
 'more': 52,
 'very': 53,
 'when': 54,
 'she': 55,
 'up': 56,
 'can': 57,
 'b': 58,
 'time': 59,
 'no': 60,
 'even': 61,
 'my': 62,
 'would': 63,
 'which': 64,
 'story': 65,
 'only': 66,
 'really': 67,
 'see': 68,
 'their': 69,
 'had': 70,
 'were': 71,
 'me': 72,
 'well': 73,
 'we': 74,
 'than': 75,
 'much': 76,
 'been': 77,
 'get': 78,
 'bad': 79,
 'will': 80,
 'people': 81,
 'do': 82,
 'also': 83,


In [33]:
imdb_sentences = []
table = str.maketrans('','',string.punctuation)

for item in train_data:
    sentence = str(item['text'].decode('UTF-8').lower())
    soup = BeautifulSoup(sentence)
    sentence = soup.get_text()
    words = sentence.split()
    filtered_sentence = ''

    for word in words:
        word = word.translate(table)

        if word not in stopwords:
            filtered_sentence = filtered_sentence + word + ''

        imdb_sentences.append(filtered_sentence)

tokenizer = Tokenizer(num_words=25000)
tokenizer.fit_on_texts(imdb_sentences)

sequences = tokenizer.texts_to_sequences(imdb_sentences)

In [34]:
tokenizer.word_index

{'movie': 1,
 'film': 2,
 'first': 3,
 'saw': 4,
 'im': 5,
 'well': 6,
 'just': 7,
 'am': 8,
 'watched': 9,
 'sawmovie': 10,
 'think': 11,
 'like': 12,
 'only': 13,
 'thought': 14,
 'ok': 15,
 'dont': 16,
 'can': 17,
 'seen': 18,
 'ive': 19,
 'say': 20,
 'love': 21,
 'smallvilleepisodejusticebestepisodesmallville': 22,
 'smallvilleepisodejusticebestepisodesmallvillefavoriteepisodesmallville': 23,
 'wow': 24,
 'read': 25,
 'dontknow': 26,
 'know': 27,
 'story': 28,
 'sawfilm': 29,
 'loved': 30,
 'enjoyed': 31,
 'who': 32,
 'movies': 33,
 'believe': 34,
 'firstsaw': 35,
 'okay': 36,
 'went': 37,
 'worst': 38,
 'watching': 39,
 'great': 40,
 'best': 41,
 'admit': 42,
 'yes': 43,
 'found': 44,
 'theres': 45,
 'remember': 46,
 'spoilers': 47,
 'bad': 48,
 'liked': 49,
 'rented': 50,
 'heard': 51,
 'now': 52,
 'show': 53,
 'agree': 54,
 'once': 55,
 'may': 56,
 'see': 57,
 'iveseen': 58,
 'man': 59,
 'watchedmovie': 60,
 'greatmovie': 61,
 'far': 62,
 'being': 63,
 'justsaw': 64,
 'cansay': 